// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1_clase;

import java.lang.Object;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/************************************************************/
/**
 * 
 */
public class Client {
	/**
	 * 
	 */
	private String nume;
	/**
	 * 
	 */
	private String prenume;
	/**
	 * 
	 */
	private int varsta;
	/**
	 * 
	 */
	
	private int nrProduse;
	
	private boolean readyCheckout;
	
	private boolean doneCheckout;
	
	public Produs[] produs;
	/**
	 * 
	 */
	public Cont cont;

	/**
	 * 
	 */
	public void afisareClient() {
		
		System.out.println("Client [nume=" + nume + ", prenume=" + prenume + ", varsta=" + varsta + ", produs="
				+ Arrays.toString(produs) + ", cont=" + cont + "]");
		
	}

	public void aduagareProdus(Produs P) {
		
		this.produs[nrProduse++] = P;
	}
	
	public void stergereProdus(Produs p) {
		
		List<Produs> tempList = new ArrayList<>(Arrays.asList(this.produs));
		tempList.remove(p);
		this.produs = tempList.toArray(new Produs[0]);
		
	}
	
	/**
	 * 
	 */
	public float totalPlata() {
		
		float total = 0;
		for(int i = 0; i < produs.length; i++) {
			
			total += produs[i].getPret();
		}
		
		return total;
	}

	/**
	 * 
	 */
	public void afisareProduse() {
		
		for(int i = 0; i < produs.length; i++) {
			
			produs[i].afisareProdus();
		}
	}

	/**
	 * 
	 */
	public void finalizareComanda() {
		
		System.out.println("CLientul " + nume + " " + prenume + " are de platit " + totalPlata() + " si este pregatit de checkout");
		afisareProduse();
		
		readyCheckout = true;
		
	}

	/**
	 * 
	 */
	public void anulareComanda() {
		
		System.out.println("Comanda a fost anulata!");
	}

	/**
	 * 
	 * @param nume 
	 * @param prenume 
	 * @param varsta 
	 */
	public void modificareDate(String nume, String prenume, int varsta) {
	}

	public int nrProduse(Produs produs) {
		
		
		return 0;
	}

	
	public Client(String nume, String prenume, int varsta, Produs[] produs, Cont cont) {
		super();
		this.nume = nume;
		this.prenume = prenume;
		this.varsta = varsta;
		this.produs = produs;
		this.cont = cont;
		this.readyCheckout = false;
		this.doneCheckout = false;
		this.nrProduse = this.produs.length;
		
	}

	public String getNume() {
		return nume;
	}

	public int getNrProduse() {
		return nrProduse;
	}

	public void setNrProduse(int nrProduse) {
		this.nrProduse = nrProduse;
	}

	public void setNume(String nume) {
		this.nume = nume;
	}

	public String getPrenume() {
		return prenume;
	}

	public void setPrenume(String prenume) {
		this.prenume = prenume;
	}

	public int getVarsta() {
		return varsta;
	}

	public void setVarsta(int varsta) {
		this.varsta = varsta;
	}

	public Produs[] getProdus() {
		return produs;
	}

	public void setProdus(Produs[] produs) {
		this.produs = produs;
	}

	public Cont getCont() {
		return cont;
	}

	public void setCont(Cont cont) {
		this.cont = cont;
	}

	public boolean isReadyCheckout() {
		return readyCheckout;
	}

	public void setReadyCheckout(boolean readyCheckout) {
		this.readyCheckout = readyCheckout;
	}

	public boolean isDoneCheckout() {
		return doneCheckout;
	}

	public void setDoneCheckout(boolean doneCheckout) {
		this.doneCheckout = doneCheckout;
	}
	
}
