// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1_clase;

import java.util.Arrays;

/************************************************************/
/**
 * 
 */
public class Client {
	/**
	 * 
	 */
	private String nume;
	/**
	 * 
	 */
	private String prenume;
	/**
	 * 
	 */
	private int varsta;
	/**
	 * 
	 */
	public Produs[] produs;
	/**
	 * 
	 */
	public Cont cont;

	/**
	 * 
	 */
	public void afisareClient() {
		
		System.out.println("Client [nume=" + nume + ", prenume=" + prenume + ", varsta=" + varsta + ", produs="
				+ Arrays.toString(produs) + ", cont=" + cont + "]");
		
	}


	/**
	 * 
	 */
	public float totalPlata() {
		
		float total = 0;
		for(int i = 0; i < produs.length; i++) {
			
			total += produs[i].getPret();
		}
		
		return total;
	}

	/**
	 * 
	 */
	public void afisareProduse() {
		
		for(int i = 0; i < produs.length; i++) {
			
			produs[i].afisareProdus();
		}
	}

	/**
	 * 
	 */
	public void finalizareComanda() {
		
		System.out.println("CLientul " + nume + " " + prenume + " are de platit " + totalPlata());
		afisareProduse();
		
		cont.retragere(totalPlata());
	}

	/**
	 * 
	 */
	public void anulareComanda() {
		
		System.out.println("Comanda a fost anulata!");
	}

	/**
	 * 
	 * @param nume 
	 * @param prenume 
	 * @param varsta 
	 */
	public void modificareDate(String nume, String prenume, int varsta) {
	}

	public Client(String nume, String prenume, int varsta, Produs[] produs, Cont cont) {
		super();
		this.nume = nume;
		this.prenume = prenume;
		this.varsta = varsta;
		this.produs = produs;
		this.cont = cont;
	}

	public String getNume() {
		return nume;
	}

	public void setNume(String nume) {
		this.nume = nume;
	}

	public String getPrenume() {
		return prenume;
	}

	public void setPrenume(String prenume) {
		this.prenume = prenume;
	}

	public int getVarsta() {
		return varsta;
	}

	public void setVarsta(int varsta) {
		this.varsta = varsta;
	}

	public Produs[] getProdus() {
		return produs;
	}

	public void setProdus(Produs[] produs) {
		this.produs = produs;
	}

	public Cont getCont() {
		return cont;
	}

	public void setCont(Cont cont) {
		this.cont = cont;
	}
	
}
