// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1_clase;

/************************************************************/
/**
 * 
 */
public class Client {
	/**
	 * 
	 */
	private String nume;
	/**
	 * 
	 */
	private String prenume;
	/**
	 * 
	 */
	private int varsta;
	/**
	 * 
	 */
	public Produs[] produs;
	/**
	 * 
	 */
	public Cont cont;

	/**
	 * 
	 */
	public void afisareClient() {
	}

	/**
	 * 
	 */
	public void totalPlata() {
	}

	/**
	 * 
	 */
	public void afisareProduse() {
	}

	/**
	 * 
	 */
	public void finalizareComanda() {
	}

	/**
	 * 
	 */
	public void anulareComanda() {
	}

	/**
	 * 
	 * @param nume 
	 * @param prenume 
	 * @param varsta 
	 */
	public void modificareDate(String nume, String prenume, int varsta) {
	}
}
