// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1_clase;

/************************************************************/
/**
 * 
 */
public class Cont {
	/**
	 * 
	 */
	private String IBAN;
	/**
	 * 
	 */
	private float suma;
	/**
	 * 
	 */
	private boolean activ;
	/**
	 * 
	 */
	private String dataExpirarii;
	/**
	 * 
	 */
	public String CVV;

	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 * @param suma 
	 */
	public void retragere(float suma) {
	}

	/**
	 * 
	 * @param suma 
	 */
	public void adaugare(float suma) {
	}

	/**
	 * 
	 */
	public void blocare() {
	}

	/**
	 * 
	 * @param newDate 
	 */
	public void extindereValabiliate(String newDate) {
	}
}
