// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1_clase;

/************************************************************/
/**
 * 
 */
public class ECommerce {
	/**
	 * 
	 */
	protected String Nume;
	/**
	 * 
	 */
	protected int numarAngajati;
}
