// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1_clase;

/************************************************************/
/**
 * 
 */
public class Emag extends ECommerce {
	/**
	 * 
	 */
	public Cont cont;
	/**
	 * 
	 */
	public ItemCatalog[] itemCatalog;
	/**
	 * 
	 */
	public Client[] client;

	/**
	 * 
	 * @param produs 
	 */
	public void disponibil(Produs produs) {
	}

	/**
	 * 
	 */
	public void afisareStoc() {
	}

	/**
	 * 
	 */
	public void afisareVenit() {
	}

	/**
	 * 
	 * @param client 
	 */
	public void anulareComandaClient(Client client) {
	}

	/**
	 * 
	 * @param client 
	 */
	public void restituieBani(Client client) {
	}

	/**
	 * 
	 * @param client 
	 */
	public void generareFactura(Client client) {
	}
}
