// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1_clase;

/************************************************************/
/**
 * 
 */
public class ItemCatalog {
	/**
	 * 
	 */
	private int cantitate;
	/**
	 * 
	 */
	public Produs produs;

	/**
	 * 
	 * @param cantitate 
	 */
	public void ScadereStoc(int cantitate) {
	}

	/**
	 * 
	 * @param catitate 
	 */
	public void crestereStoc(int catitate) {
	}
}
