// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1_clase;

/************************************************************/
/**
 * 
 */
public class Produs {
	/**
	 * 
	 */
	private String nume_produs;
	/**
	 * 
	 */
	private float pret;
	/**
	 * 
	 */
	private String furnizor;
	/**
	 * 
	 */
	private float rating;
	/**
	 * 
	 */
	private Categorie categorie;
	/**
	 * 
	 */
	private String descriere;

	/**
	 * 
	 */
	public void afisareProdus() {
	}

	/**
	 * 
	 * @param procent 
	 */
	public void diminuarePret(float procent) {
	}

	/**
	 * 
	 * @param procent 
	 */
	public void cresterePret(float procent) {
	}
}
